kid's saved profile
JULIERAJ/KIDS-FIRST-Front pull request #105
Opened 2024-08-31 08:04 UTC by swathivt

## One Line Description
Implemented Hardcoded Saved Kid Profile

## Test Steps
1. Open the application.
2. Navigate to the "Saved Kid Profile" section.(http://localhost:3000/savedkidprofile)

## UI/UX Outcome
- expected output
![expectedSavedKidProfile](https://github.com/user-attachments/assets/2d1c5e92-4836-49e2-a9ef-6e902972912d)
 actual output
![savedKidProfile](https://github.com/user-attachments/assets/27c76b68-fde2-426f-b866-bb0e6e395395)

## Checklist
- [x] Pull Request title includes the issue number and a brief description of the change.
- [x] All changes should be tested and verified to work correctly.
- [x] Code follows frontend best practices.
- [x] Branch names follow the conventions in the contributing file.
- [x] Commit messages follow the naming conventions in the contributing file.

2024-09-02 23:32 UTC, pandjyoti approved these changes

2024-09-03 00:00 UTC, ElenaCherpakova requested changes
@swathivt Overall, good job, but some corrections are needed. There are missing spaces, and the button is larger compared to the Figma design.

2024-09-03 00:00 UTC, ElenaCherpakova commented on src/components/KidsSavedProfile/SavedKidProfile.jsx
> +import edit from '../../media/icons/edit.svg';
@swathivt check how we import media in short way

2024-09-03 00:00 UTC, ElenaCherpakova commented on src/components/KidsSavedProfile/SavedKidProfile.jsx
> +          <CustomButton
@swathivt Check the custom button to see which props this component receives. You may not need to style it again. Additionally, your button is larger compared to the Figma design.

2024-09-03 00:00 UTC, ElenaCherpakova commented on src/components/KidsSavedProfile/SavedKidProfile.jsx
> +          <Col xs={3} md={1} className={styles['add-kid-label']}>
@swathivt  Consider how you can optimize this column. Do you think you could create an array and map it?

2024-09-03 00:00 UTC, ElenaCherpakova commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  width: Fill (1, 120px) px;
@swathivt What is this syntax?

2024-09-03 00:00 UTC, ElenaCherpakova commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  height: Fixed (328px) px;
@swathivt What is this syntax?

2024-09-03 00:00 UTC, ElenaCherpakova commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  direction: rtl;
@swathivt pls check this link ` https://developer.mozilla.org/en-US/docs/Web/CSS/direction`

2024-09-03 00:00 UTC, ElenaCherpakova commented on src/App.jsx
> +          <Route path= '/savedkidprofile' element={<SavedKidProfile />} />
@swathivt the path is wrong, please take a look on back end and fix it pls

2024-09-05 05:54 UTC, swathivt commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  height: Fixed (328px) px;
copied from figma design

2024-09-05 05:54 UTC, swathivt commented on src/components/KidsSavedProfile/SavedKidProfile.jsx
> +import edit from '../../media/icons/edit.svg';
import edit from '@media/icons/edit.svg'; is this correct?

2024-09-05 06:25 UTC, swathivt commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  width: Fill (1, 120px) px;
removed this line "list-style: none;"

2024-09-05 07:05 UTC, swathivt commented on src/components/KidsSavedProfile/SavedKidProfile.jsx
> +          <Col xs={3} md={1} className={styles['add-kid-label']}>
created infoList array and used map function

2024-09-05 07:29 UTC, swathivt commented on src/components/KidsSavedProfile/SavedKidProfile.jsx
> +          <CustomButton
Used this style <Col className={styles['add-kid-button-col']}> to push the button to the right side. Modified the button size according to the Figma Design.

2024-09-05 20:31 UTC, ElenaCherpakova commented on src/components/KidsSavedProfile/SavedKidProfile.jsx
> +import edit from '../../media/icons/edit.svg';
yes

2024-09-05 20:38 UTC, ElenaCherpakova commented on src/components/KidsSavedProfile/SavedKidProfile.jsx
> +          <CustomButton
@swathivt We have CustomButton component please check what props this button recievies in your module.css you style this button again by using `add-kid-button`

2024-09-05 20:53 UTC, ElenaCherpakova requested changes, later dismissed

2024-09-05 20:53 UTC, ElenaCherpakova commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  height: Fixed (328px) px;
@swathivt avoid copying style from figma some of properties doesnt exist in css

2024-09-05 20:53 UTC, ElenaCherpakova commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  width: Fill (1, 120px) px;
@swathivt this syntaxt doesnt exist in css   `width: Fill (1, 120px) px;`

2024-09-07 08:29 UTC, swathivt commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  width: Fill (1, 120px) px;
corrected

2024-09-07 08:53 UTC, swathivt commented on src/components/KidsSavedProfile/SavedKidProfile.jsx
> +          <CustomButton
done

2024-09-07 09:07 UTC, swathivt commented on src/App.jsx
> +          <Route path= '/savedkidprofile' element={<SavedKidProfile />} />
fixed

2024-09-15 19:28 UTC, nandini92 commented on src/App.jsx
> +          <Route path= '/savedkidprofile' element={<SavedKidProfile />} />
hi @swathivt, please move the route to under protected routes as this will be loaded as part of Kid's Info list:
![image](https://github.com/user-attachments/assets/7799e382-29ec-4df8-8ac6-e28744573d04)

2024-09-15 19:43 UTC, nandini92 commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  font-size: var(--fontsizeXS);
Please remove the font-family and font-size settings as there is no global setting for --fontfamily and fontsizeXS.  As per figma, you can set the pixel value for font-size of kid-dob to 14px:
https://www.figma.com/design/qUBlZE5TIgpqShKTVcSvRo/Kids-First-WITT(Desktop)?node-id=7358-2217&t=gmu110WaJtwRwFWj-4

2024-09-15 19:43 UTC, nandini92 commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  font-size: var(--fontsizeS);
Please remove the font-family and font-size settings as there is no global setting for --fontfamily and fontsizeXS.

2024-09-15 19:43 UTC, nandini92 commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  font-size: var(--fontsizeS);
Please remove the font-family and font-size settings as there is no global setting for --fontfamily and fontsizeXS.

2024-09-15 19:49 UTC, nandini92 commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  font-size: var(--fontsizeL);
Please remove the font-family and font-size settings as there is no global setting for --fontfamily and fontsizeXS.  Please set font-size to 24px (matching the Kid profile name as per figma design.

2024-09-16 19:22 UTC, swathivt commented on src/App.jsx
> +          <Route path= '/savedkidprofile' element={<SavedKidProfile />} />
Moved to under protected route.

2024-09-16 19:23 UTC, swathivt commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  font-size: var(--fontsizeXS);
removed global settings for --fontfamily and fontsizeXS. font-size set to 14px;

2024-09-16 19:24 UTC, swathivt commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  font-size: var(--fontsizeS);
removed

2024-09-16 19:24 UTC, swathivt commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  font-size: var(--fontsizeS);
removed

2024-09-16 19:24 UTC, swathivt commented on src/components/KidsSavedProfile/SavedKidProfile.module.css
> +  font-size: var(--fontsizeL);
removed

2024-09-16 21:59 UTC, nandini92 approved these changes

2024-09-17 16:04 UTC, merged