Feat/120/create default page for album
JULIERAJ/KIDS-FIRST-Front pull request #123
Opened 2024-10-19 21:08 UTC by swathivt

## One Line Description
create default page for album

## Test Steps
1. Open the application.
2. Navigate to the sidebar and click on Album

## actual UI/UX Outcome
![ActualOutPut](https://github.com/user-attachments/assets/dae69a45-7ca8-4956-b182-656ce49268d7)

## expected UI/UX Outcome
![ExpectedOutCome](https://github.com/user-attachments/assets/5fa8dabd-0ce9-4c60-a8a8-1719d2705c4a)

## Checklist
- [ ] Pull Request title includes the issue number and a brief description of the change.
- [ ] All changes should be tested and verified to work correctly.
- [ ] Code follows frontend best practices.
- [ ] Branch names follow the conventions in the contributing file.
- [ ] Commit messages follow the naming conventions in the contributing file.

2024-10-19 21:13 UTC, pandjyoti approved these changes

2024-10-21 17:31 UTC, Alaleh-kash submitted a review, later dismissed

2024-10-26 17:28 UTC, nandini92 requested changes
Please review comments on code. There are many new lines created which are not needed. Also, the CSS for Album page needs to be reviewed.

2024-10-26 17:28 UTC, nandini92 commented on src/components/Dashboard/Calendar/KFCalendar/DayEvent/DayEvent.jsx
> +
Please remove extra line.

2024-10-26 17:28 UTC, nandini92 commented on src/components/Dashboard/Calendar/KFCalendar/EventModal/EventModal.jsx
> +
Please remove extra line.

2024-10-26 17:28 UTC, nandini92 commented on src/components/Dashboard/Calendar/KFCalendar/KFCalendar.jsx
> +
Please remove extra line.

2024-10-26 17:28 UTC, nandini92 commented on src/components/Dashboard/Calendar/KFCalendar/Toolbar/KFToolbar.jsx
> +
Please remove extra line.

2024-10-26 17:28 UTC, nandini92 commented on src/components/Dashboard/Kids/ModalKid/ModalKid.jsx
> +
Please remove extra line.

2024-10-26 17:28 UTC, nandini92 commented on src/components/shared/Footer/Footer.jsx
> +
Please remove extra line.

2024-10-26 17:28 UTC, nandini92 commented on src/components/shared/Header/Header.jsx
> +
Please remove extra line.

2024-10-26 17:28 UTC, nandini92 commented on src/components/Dashboard/Album/Album.module.css
> +}
Background color for container is missing.  Please refer to Kid.jsx and kids.module.css on how to create container.

![image](https://github.com/user-attachments/assets/ca97613a-5984-4e1a-ad08-659304336b14)

2024-10-26 17:28 UTC, nandini92 commented on src/components/Dashboard/Album/Album.module.css
> +  font-size: 16px;
Please use rem instead of px for font size.

2024-10-26 17:28 UTC, nandini92 commented on src/components/Dashboard/Album/Album.module.css
> +  height: 100vh;
No need for .parent-container. Please refer to Kid.jsx and kids.module.css on how to create container.

2024-10-29 07:56 UTC, swathivt commented on src/components/Dashboard/Album/Album.module.css
> +}
done

2024-10-29 07:57 UTC, swathivt commented on src/components/Dashboard/Kids/ModalKid/ModalKid.jsx
removed extra line

2024-11-03 19:17 UTC, nandini92 approved these changes
Great Job @swathivt !

2024-11-03 19:17 UTC, merged