Feat/122/album page with content
JULIERAJ/KIDS-FIRST-Front pull request #129
Opened 2024-11-02 07:03 UTC by swathivt

## One Line Description
Create album page with content

## Test Steps
1. Open the application.
2. Navigate to the '/dashboard/albumContent'
3. Ensure that all buttons are fully clickable.

## UI/UX Expected Outcome
-[ [Insert relevant screenshots or videos here]
](https://www.figma.com/proto/qUBlZE5TIgpqShKTVcSvRo/Kids-First-WITT(Desktop)?node-id=15054-53609&node-type=frame&t=aYew8hhwa0W1DA6l-0&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=14909%3A60377)

Actual Outcome
![AlbumPageContent](https://github.com/user-attachments/assets/a6e35bab-dc63-4af7-851c-b3333139eca1)

## Checklist
- [ ] Pull Request title includes the issue number and a brief description of the change.
- [ ] All changes should be tested and verified to work correctly.
- [ ] Code follows frontend best practices.
- [ ] Branch names follow the conventions in the contributing file.
- [ ] Commit messages follow the naming conventions in the contributing file.

2024-11-02 07:13 UTC, pandjyoti approved these changes

2024-11-09 16:28 UTC, nandini92 requested changes
Great job @swathivt ! There are some minor changes to be made, otherwise all is good. :)

2024-11-09 16:28 UTC, nandini92 commented on src/components/Dashboard/AlbumPageContent/AlbumContent.jsx
> +                  <Dropdown.Item href="/oldest">Oldest</Dropdown.Item>
Please fix font size for dropdown text:
![image](https://github.com/user-attachments/assets/1d9d1144-2c30-4588-ba1c-bd7f160c2752)

Expected (note: please convert to REM):
![image](https://github.com/user-attachments/assets/ac5bc75a-2013-4a7c-85c1-300dcf08da60)

2024-11-09 16:28 UTC, nandini92 commented on src/components/shared/Modal/DeleteMessageModal.jsx
> +          <p className={modalStyles['modal-message']}>{message}</p>
Need to remove default bottom margin:
![image](https://github.com/user-attachments/assets/7ea7c2ac-fe87-4f41-8642-b76676430626)

Expectation:
![image](https://github.com/user-attachments/assets/b4438663-b7c3-4d73-8b7c-d4cc656fa560)

2024-11-10 00:46 UTC, nandini92 approved these changes

2024-11-10 00:46 UTC, merged