Fix: edit kid photo dropdown
JULIERAJ/KIDS-FIRST-Front pull request #139
Opened 2024-11-18 19:46 UTC by Judithlourde

One Line Description
Edit kid photo dropdown style

Requirements
- Expectation: Please refer to [Figma ](https://www.figma.com/design/qUBlZE5TIgpqShKTVcSvRo/Kids-First-WITT(Desktop)?node-id=14512-130900&t=seuHdaHYobfLzmRZ-4)design.
- NOTE : There is no Figma design for effect of mousing over dropdown items. Check with designers on expectation.

Notes
There is a Figma design illustrating the effect of mousing over dropdown items, which can be found here:
https://www.figma.com/proto/qUBlZE5TIgpqShKTVcSvRo/Kids-First-WITT(Desktop)?node-id=14512-130520&node-type=frame&t=iItelqg7RezdCKWy-0&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=14909%3A60377

Test Steps
1. Open the application. 
2. Navigate to the kid's info page
3. Check Edit Kid Photo dropdown design 

UI/UX Outcome
![image](https://github.com/user-attachments/assets/5a115f61-0d68-45ba-bb93-fb68ff437f9c)

Checklist
- [x] Pull Request title includes the issue number and a brief description of the change.
- [x] All changes should be tested and verified to work correctly.
- [x] Code follows frontend best practices.
- [x] Branch names follow the conventions in the contributing file.
- [x] Commit messages follow the naming conventions in the contributing file.

2024-11-19 23:00 UTC, nandini92 requested changes
Great job Judith!  All that is remaining is some text style changes.

2024-11-19 23:00 UTC, nandini92 commented on src/components/Dashboard/Kids/KidsInfo/Dropdown/PhotoOptionsDropdown.module.css
>  }
Please also review the font sizing and alignment ([Figma](https://www.figma.com/design/qUBlZE5TIgpqShKTVcSvRo/Kids-First-WITT(Desktop)?node-id=13353-54946&t=l5ZrRszaMUTsFk4z-4)).
![image](https://github.com/user-attachments/assets/bdc9effc-2be7-4fde-9226-4bb857bf3c7e)
![image](https://github.com/user-attachments/assets/b6a7d957-8565-41da-adee-454d71bfacd5)

2024-11-20 18:55 UTC, Judithlourde commented on src/components/Dashboard/Kids/KidsInfo/Dropdown/PhotoOptionsDropdown.module.css
>  }
Thank you @nandini92 for letting me know. I’ve addressed the changes you requested. Let me know if there’s anything else!
![Snag_2661830e](https://github.com/user-attachments/assets/0928f406-2e3e-4677-b29d-fbd83cc32be4)

2024-11-23 20:49 UTC, nandini92 approved these changes
Great job @Judithlourde ! This PR is approved!

2024-11-23 20:50 UTC, pandjyoti approved these changes

2024-11-23 20:55 UTC, merged