ref :Lifting state in dashboard
JULIERAJ/KIDS-FIRST-Front pull request #22
Opened 2024-07-08 20:16 UTC by Nassimancer

One Line Description
Lifting State in Dashboard
Requirements
Create handler function(s) in the parent component to avoid setting state in the child component. The state should be managed in the parent component
Test Steps
Check if the navigation in the sidebar works correctly
Checklist

- [ ] Pull Request title includes the issue number and a brief description of the change.
- [ ] All changes should be tested and verified to work correctly.
- [ ] Code follows frontend best practices.
- [ ] Branch names follow the conventions in the contributing file.
- [ ] Commit messages follow the naming conventions in the contributing file.

2024-07-08 20:37 UTC, AnnaSolovykh requested changes
This is small remark - please adjust Sidebar component accordingly with the new prop name.

Overall: **great job, you got it!** I was so happy to see your PR, happy you've made it!

2024-07-08 20:37 UTC, AnnaSolovykh commented on src/pages/Dashboard/Dashboard.jsx
> +      <Sidebar setTitle={handleTitleChange} />
It is better to use `onTitleChange` for the prop name when passing it to the child component. 

<Sidebar onTitleChange ={handleTitleChange} />

2024-07-09 15:57 UTC, AnnaSolovykh commented
The prop name should be called **onTitleChange**. This **prop** is what you send to the child component.

The function should be named using the **handle** prefix, such as handleSomething (e.g., **handleClick**, **handleTitleChange**). The prop should be called using the **on** prefix, such as **onClick**, **onTitleChange**.

`onTitleChange={handleTitleChange}`

In this example, **onTitleChange** is a prop, and **handleTitleChange** is a handler function.

Why is it best practice to use the **on** prefix for prop names? This is because you're **attaching a listener to the function, indicating that this function is responsible for handling an event.**

_The on prefix is a widely recognized convention in event handling. By using onTitleChange, it signals to anyone reading your code that this prop is an event handler. Using on for props and handle for functions helps maintain a clear separation between the component's interface (props) and its internal implementation (handler functions). It indicates that the prop (onTitleChange) is a callback function meant to handle events triggered by the child component._

2024-07-13 00:11 UTC, AnnaSolovykh approved these changes
Well done! ![Spongebob Many Thumbs](https://media1.giphy.com/media/3o7abGQa0aRJUurpII/giphy.gif?cid=47028fa8sx12d824xrvy8zo8bq3w00f23hoj11gqqzus7q0f&ep=v1_gifs&rid=giphy.gif&ct=g)

2024-07-13 01:34 UTC, ElenaCherpakova approved these changes

2024-07-13 01:37 UTC, merged