Feat/137/new account verification design
JULIERAJ/KIDS-FIRST-Front pull request #42
Opened 2024-07-15 16:03 UTC by VrushaliHaldankar01

Feat/137/new account verification design
Follow the design in Figma in the following pages: Email Verified, Link Expired, Something went wrong
Add functionality to handle the logic in the flow
[Figma](https://www.figma.com/design/qUBlZE5TIgpqShKTVcSvRo/Kids-First-WITT(Desktop)?node-id=0-1&t=J7tX1aYPuECQ1hVW-0)
Email verified
![image](https://github.com/user-attachments/assets/7749c705-5c70-4ba1-9c68-e9adc3f13eee)
design matches with the figma design 
![image](https://github.com/user-attachments/assets/e8bcf445-d732-4bfb-9227-4632da8677a8)
Something went wrong-figma
![image](https://github.com/user-attachments/assets/143d718e-3deb-43d7-9857-94f1f2a36cc3)
as per code
![image](https://github.com/user-attachments/assets/86354d27-19dd-43c9-bae8-2c673dd99921)

Code follows frontend best practices.
Branch names follow the conventions in the contributing file.
Commit messages follow the naming conventions in the contributing file.

steps:
In order to test design fast you need to set the jwt email token to "1 minute" in the backend
in order to check something went wrong page -delete the entry from the database and try to click the link again that you got in your mailbox(when you sign up you will get link in the gmail).

2024-07-16 15:53 UTC, AnnaSolovykh requested changes
I  can clearly see the mismatch in the design and outcome. Can you see it?

2024-07-17 01:04 UTC, ElenaCherpakova commented
Here is the issue with styling
![Screen Shot 2024-07-16 at 9 03 02 PM](https://github.com/user-attachments/assets/cf2ae6bf-3391-4ce8-883b-5c6973cfbb02)
![Screen Shot 2024-07-16 at 9 03 55 PM](https://github.com/user-attachments/assets/a5b233ac-4bc4-468c-8ead-535b9fe82fc2)

2024-07-17 01:34 UTC, ElenaCherpakova requested changes

2024-07-17 01:34 UTC, ElenaCherpakova commented on .eslintrc.json
> +    "linebreak-style": 0,
May i know why you changed it to 0?

2024-07-17 01:34 UTC, ElenaCherpakova commented on .gitignore
> +.env.example
why did you add` .env.example` to .gitignore? How other upcoming developers would know what keys they have to obtain in order to setup environment?

2024-07-17 01:34 UTC, ElenaCherpakova commented on src/pages/Activate/Activate.jsx
> +                <div className={styles.emailverified}>
During one of our recent meetings, we talked about avoiding the use of divs and transitioning to more semantic tags like` main`, `article` `section` for better web accessibility. Additionally, we discussed the naming convention for classes.
Currently, you have `emailverifiedpage` same with others. To enhance readability and maintain consistency, we decided to use a `hyphenated format,` for example, email-verified-outer-container.
I believe this will make our code more understandable and maintainable.

2024-07-25 22:29 UTC, AnnaSolovykh commented
<img width="1648" alt="Screenshot 2024-07-25 at 17 55 44" src="https://github.com/user-attachments/assets/b5c199e6-155a-466e-b6dc-b61b63be6605">
<img width="1723" alt="Screenshot 2024-07-25 at 18 00 08" src="https://github.com/user-attachments/assets/5c27ee35-89b8-4205-ba21-753f36c952fc">

2024-07-25 22:43 UTC, pandjyoti approved these changes

2024-07-27 01:43 UTC, AnnaSolovykh approved these changes

2024-07-27 02:29 UTC, ElenaCherpakova approved these changes

2024-07-27 12:10 UTC, merged