Refactor/4/css styles and imports of components
JULIERAJ/KIDS-FIRST-Front pull request #6
Opened 2024-07-02 01:36 UTC by ElenaCherpakova

## One Line Description
- Set up jsconfig to shorten path lengths.
- Include an index.js file for every component.
- Eliminate unused styles and convert them to module.css.

## Test Steps
1. Once PR please `run npm i `to install dependencies.
2. Open the application.
3. Check if you don't have any warnings such as eslint and if the paths of some components can't be resolved or are undefined.

2024-07-02 02:41 UTC, AnnaSolovykh approved these changes
Great job!  
That is impressive! 👏🏻✨

2024-07-02 06:47 UTC, S-chahine commented on src/components/Dashboard/Calendar/KFCalendar/DayEvent/DayEvent.jsx
> +      <span className={styles.circle} style={circleStyle}>
Update the <span> element with the following inline style to ensure centered content within .circle:
<span className={styles.circle} style={{
        ...circleStyle,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
      }}>
        {kidsName && kidsName.charAt(0).toUpperCase()}
      </span>

2024-07-02 06:49 UTC, S-chahine commented on src/components/Dashboard/Calendar/KFCalendar/WeekEvent/WeekEvent.jsx
> +      <span className={`${styles.circle} circle`} style={circleStyle}>
Update the <span> element with the following inline style to ensure centered content within .circle:
<span className={styles.circle} style={{
        ...circleStyle,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
      }}>
        {kidsName && kidsName.charAt(0).toUpperCase()}
      </span>

2024-07-02 06:50 UTC, S-chahine commented on src/components/Dashboard/Calendar/KFCalendar/WeekEvent/WeekEvent.module.css
> +  margin-top: 10px;
adjust: margin-left: 15px;

2024-07-02 06:57 UTC, S-chahine commented on src/components/Dashboard/Calendar/KFCalendar/DayEvent/DayEvent.module.css
> +  margin-left: 0px;
adjust
 margin-left: 5px;

2024-07-02 06:57 UTC, S-chahine commented on src/components/Dashboard/Calendar/KFCalendar/DayEvent/DayEvent.module.css
> +  top: 5px;
adjust 
top: -10px;

2024-07-02 06:58 UTC, S-chahine commented on src/components/Dashboard/Calendar/KFCalendar/DayEvent/DayEvent.module.css
> +  margin-left: 0;
adjust
margin-left: 5px;

2024-07-02 06:59 UTC, S-chahine commented on src/components/Dashboard/Calendar/KFCalendar/DayEvent/DayEvent.module.css
> +}
add:
width: 100%;

2024-07-02 06:59 UTC, S-chahine commented on src/components/Dashboard/Calendar/KFCalendar/DayEvent/DayEvent.module.css
> +  top: 10px;
adjust
top: 0px;

2024-07-02 07:00 UTC, S-chahine commented on src/components/Dashboard/Calendar/KFCalendar/DayEvent/DayEvent.module.css
> +}
add
position: relative;

2024-07-02 07:04 UTC, S-chahine requested changes
Great job Elena! We're almost there; just a bit of styling adjustment, and it'll be perfect.

2024-07-02 13:42 UTC, ElenaCherpakova commented on src/components/Dashboard/Calendar/KFCalendar/WeekEvent/WeekEvent.jsx
> +      <span className={`${styles.circle} circle`} style={circleStyle}>
It was added into circle class in module.css for weekEvent

2024-07-02 13:58 UTC, ElenaCherpakova commented on src/components/Dashboard/Calendar/KFCalendar/WeekEvent/WeekEvent.jsx
> +      <span className={`${styles.circle} circle`} style={circleStyle}>
✅ added to modules.css under the circle class

2024-07-02 13:58 UTC, ElenaCherpakova commented on src/components/Dashboard/Calendar/KFCalendar/DayEvent/DayEvent.jsx
> +      <span className={styles.circle} style={circleStyle}>
✅ added to modules.css under the circle class

2024-07-02 17:08 UTC, AnnaSolovykh approved these changes

2024-07-03 16:29 UTC, S-chahine approved these changes
Great job Elena!

2024-07-03 17:37 UTC, merged