Feat/65/dashboard homepage design
JULIERAJ/KIDS-FIRST-Front pull request #74
Opened 2024-07-31 23:09 UTC by VrushaliHaldankar01

# PR Template Frontend

## One Line Description
Feat/65/dashboard homepage design
Designing of Home dashboard page of kids first

## UI/UX Outcome
- Add any relevant screenshots or videos to demonstrate the UI/UX changes.
- 
![image](https://github.com/user-attachments/assets/d8e88ec7-f1bb-4841-9100-d705aa45e916)

2024-08-01 13:24 UTC, AnnaSolovykh requested changes, later dismissed
Vrushali, great job! Please review the comments and make the changes needed. Also, please look into the icon issue. Its position and color don't match the Figma design. Please export the icon as SVG from Figma.
<img width="1386" alt="Screenshot 2024-08-01 at 09 23 25" src="https://github.com/user-attachments/assets/6de0229a-d3e4-4415-a6ef-024d75c6e140">
<img width="941" alt="Screenshot 2024-08-01 at 09 23 39" src="https://github.com/user-attachments/assets/31df6d2a-4f82-4c42-9b29-921e4d555a5f">

2024-08-01 13:24 UTC, AnnaSolovykh commented on src/components/Dashboard/HomeDashboard/HomeDashboard.module.css
> +.dashboard{
To improve code readability and maintain consistency in our styling, we should add a space between the class selector and the opening brace.

2024-08-01 13:24 UTC, AnnaSolovykh commented on src/components/Dashboard/HomeDashboard/HomeDashboard.module.css
> +  .pagewindow{
The name` .pagewindow` does not adhere to our project's naming conventions. For consistency, it should be renamed to match our standard naming scheme. For example, if we use kebab-case for class names, it should be renamed to` .page-window.`

2024-08-01 13:24 UTC, AnnaSolovykh commented on src/components/Dashboard/HomeDashboard/HomeDashboard.jsx
> +        <div className={styles.pagewindow}>
For containers we use Bootstrap containers - please refer to the projects' best practices.

2024-08-01 13:24 UTC, AnnaSolovykh commented on src/components/shared/ui/Button/CustomButton.jsx
> +export default CustomButton;
The code modification you added is outside the scope of your current ticket. Additionally, the CustomButton component is already exported, so the added export default CustomButton; is redundant and unnecessary.

2024-08-01 13:24 UTC, AnnaSolovykh commented on src/components/shared/ui/Button/contentStyles.css
> +.icon-right-style {
Before making changes to someone else's code, you should always seek permission and get their opinion. In this case, please ask @nandini92 to review this change.

2024-08-01 13:24 UTC, AnnaSolovykh commented on src/pages/Dashboard/Dashboard.jsx
> +        </div> */}
Is there a reason to keep this commented-out code? If it's not needed, it should be removed to keep the codebase clean and maintainable. Additionally, please review the imports above and remove any that are unnecessary.

2024-08-01 13:24 UTC, AnnaSolovykh commented on src/pages/Dashboard/Dashboard.module.css
> +
The same here - this is css for the code which is not used and is commented out. Let's keep the code clean.

2024-08-01 13:24 UTC, AnnaSolovykh commented on package.json
> +    "cors": "^2.8.5",
What was the purpose behind adding cors?

2024-08-01 13:24 UTC, AnnaSolovykh commented on src/components/Dashboard/HomeDashboard/HomeDashboard.jsx
> +          <CustomButton
When we click on the button we should be redirected to the Kid's page.

2024-08-01 16:01 UTC, VrushaliHaldankar01 commented on src/components/Dashboard/HomeDashboard/HomeDashboard.jsx
> +  const [showPart, setShowPart] = useState(false);
Sure , ill edit it

2024-08-01 17:16 UTC, VrushaliHaldankar01 commented on src/components/Dashboard/HomeDashboard/HomeDashboard.jsx
> +        <div className={styles.pagewindow}>
Yes , this is the previous code , i did not modify it

2024-08-01 17:17 UTC, VrushaliHaldankar01 commented on src/components/Dashboard/HomeDashboard/HomeDashboard.jsx
> +        <div className={styles.pagewindow}>
this is the static page code which was already there

2024-08-01 18:05 UTC, AnnaSolovykh commented on src/components/Dashboard/HomeDashboard/HomeDashboard.jsx
> +        <div className={styles.pagewindow}>
This is the code you have added. In the screenshot you can see code from the dev branch from the same component, and this code is using Bootstrap. Yours should also use it. 
<img width="971" alt="Screenshot 2024-08-01 at 14 03 04" src="https://github.com/user-attachments/assets/38b47e67-8c04-42cb-8400-8e6df5fa0e0c">

2024-08-05 00:33 UTC, VrushaliHaldankar01 commented
Made changes as per the request and also imported image as svg

2024-08-22 17:36 UTC, AnnaSolovykh commented
[The solution of inheriting the color in svg in iterations](https://stackoverflow.com/questions/13000682/how-do-i-have-an-svg-image-inherit-colors-from-the-html-document)

2024-09-18 00:02 UTC, pandjyoti approved these changes

2024-09-18 01:01 UTC, pandjyoti approved these changes

2024-09-18 02:30 UTC, nandini92 requested changes

2024-09-18 02:30 UTC, nandini92 commented on src/components/Dashboard/HomeDashboard/HomeDashboard.module.css
> +    line-height: 19.2px;
Please remove these lines as they are redundant or have no effect:
    gap: 0px;
    opacity: 0px;
    font-family: var(--fontfamily);
    font-size: var(--fontsizeS);
        
     Note: I don't see any styling variables called fontfamily or fontsizeS.

2024-09-18 02:30 UTC, nandini92 commented on src/components/shared/ui/Button/buttonStyles.css
> +  height: 3.5rem; /* 56px to rem */
Please remove these lines from buttonStyles and add to the custom-button styling in HomeDashboard.module.css

2024-09-18 02:30 UTC, nandini92 commented on src/pages/Dashboard/Dashboard.jsx
> +
Please remove commented out imports.

2024-09-18 02:30 UTC, nandini92 commented on src/pages/ForgetPassword/ForgetPassword.jsx
> +      setErrMsg('There was an error with the request, please try again later.');
Figma only has this error:
![image](https://github.com/user-attachments/assets/72fa2240-4216-4614-8ca8-fb0fdeedf903)

Is this changed required?

2024-09-18 02:30 UTC, nandini92 commented on src/components/Dashboard/HomeDashboard/HomeDashboard.jsx
> +          <h1 className={styles.title}>
I believe these should be <p></p> tags as h1 title is already set in header.

2024-09-18 02:30 UTC, nandini92 commented on src/pages/Dashboard/Dashboard.module.css
> +}
Please remove this styling if it is not being used in the dashboard.

2024-09-18 02:30 UTC, nandini92 commented on src/components/shared/ui/Button/contentStyles.css
> +
Please undo extra spacing in this file.

2024-09-18 02:30 UTC, nandini92 commented on src/pages/Dashboard/Dashboard.module.css
> +.dashboard {
Please remove extra lines above .dashboard

2024-09-19 01:06 UTC, VrushaliHaldankar01 commented on src/pages/Dashboard/Dashboard.jsx
> +
Resolved

2024-09-19 01:09 UTC, VrushaliHaldankar01 commented on src/pages/ForgetPassword/ForgetPassword.jsx
> +      setErrMsg('There was an error with the request, please try again later.');
This was taken by another person earlier so dont have clear idea of changes, cant modify it

2024-09-19 01:12 UTC, VrushaliHaldankar01 commented on src/pages/Dashboard/Dashboard.module.css
> +}
Resolved

2024-09-19 01:13 UTC, VrushaliHaldankar01 commented on src/components/shared/ui/Button/contentStyles.css
> +
Resolved

2024-09-19 01:14 UTC, VrushaliHaldankar01 commented on src/pages/Dashboard/Dashboard.module.css
> +.dashboard {
Resolved

2024-09-19 01:25 UTC, VrushaliHaldankar01 commented on src/components/shared/ui/Button/buttonStyles.css
> +  height: 3.5rem; /* 56px to rem */
Resolved

2024-09-19 01:29 UTC, VrushaliHaldankar01 commented on src/components/Dashboard/HomeDashboard/HomeDashboard.jsx
> +          <h1 className={styles.title}>
I guess , i imported the styles from css and in css i mentioned as title

2024-09-19 01:45 UTC, VrushaliHaldankar01 commented on src/components/Dashboard/HomeDashboard/HomeDashboard.module.css
> +    line-height: 19.2px;
Resolved

2024-09-21 17:58 UTC, nandini92 commented on package.json
> +    "cors": "^2.8.5",
@VrushaliHaldankar01  can you please review this? Do we need cors? If not please remove from package.json

2024-09-21 18:11 UTC, nandini92 commented on src/components/Dashboard/HomeDashboard/HomeDashboard.module.css
> +    line-height: 19.2px;
@VrushaliHaldankar01  I still see the  gap and opacity setting.  We don't need gap and opacity setting for the title. 

Please also update the font-size to 1rem (16 px):
![image](https://github.com/user-attachments/assets/4a6112b5-c12a-4d83-88e4-81f1a294dbe1)

2024-09-21 18:12 UTC, nandini92 commented on src/pages/ForgetPassword/ForgetPassword.jsx
> +      setErrMsg('There was an error with the request, please try again later.');
Can you change it back in your branch and push the changes?

2024-09-22 18:09 UTC, VrushaliHaldankar01 commented on src/pages/ForgetPassword/ForgetPassword.jsx
> +      setErrMsg('There was an error with the request, please try again later.');
Yes  , ill do it

2024-09-24 20:06 UTC, nandini92 approved these changes

2024-09-25 14:48 UTC, merged