Feat:Kid's info default page
JULIERAJ/KIDS-FIRST-Front pull request #75
Opened 2024-08-01 21:11 UTC by Nassimancer

Develop a default page for the "Kid's Info" section.

## Requirements
Develop a React component for the default page.
Default page appears when the user clicks on "Kid's Info" for the first time.
Ensure that the design matches the one on Figma.

## Test Steps
- Click on 'Kid's Info' in the sidebar and check if the landing page appears.

-![image](https://github.com/user-attachments/assets/6a6a8526-59c1-4386-a71f-b645c8cea669)

## Checklist

- [ ] - [x] Pull Request title includes the issue number and a brief description of the change.
- [ ] - [x] All changes should be tested and verified to work correctly.
- [ ] - [x] Code follows frontend best practices.
- [ ] - [x] Branch names follow the conventions in the contributing file.
- [ ] - [x] Commit messages follow the naming conventions in the contributing file.

2024-08-01 21:37 UTC, InventiveBayTechnologies commented
Good

2024-08-01 21:40 UTC, pandjyoti approved these changes
Looks perfect.

2024-08-01 21:43 UTC, AnnaSolovykh requested changes
Great job! 
1) Please export icon and picture as SVG from Figma to increase the quality.
2) The icon color should match the color in Figma within any iteration - when we have focus or hover,  the color should change with the text as per Figma in the design system. All the colors are added by Nandini within the Custom button. Please consult her if you have issues.
3) Put AddFirstKid into Kids folder
4) The pathname in Sidebar should be "kids". As it will also reflect the case when the the kid is already added.
5) I can see you have added Prettier but don't see any rules for it. If you want to add let's discuss that in the group.

2024-08-01 21:43 UTC, AnnaSolovykh commented on src/components/Dashboard/AddFirstKid/AddFirstKid.module.css
> +  height: Hug (374px)px;
Hug, Fixed are Figma properties, they have nothing to do with the code and css. There are also other properties from Figma in the code that don't change anything in it - please find and delete or replace.

2024-08-01 21:43 UTC, AnnaSolovykh commented on src/components/Dashboard/AddFirstKid/AddFirstKid.module.css
> +  background: var(--fg-light-text-default-primary);
Do we this color anywhere in the code in the styles? in global styles?

2024-08-01 21:43 UTC, AnnaSolovykh commented on src/components/Dashboard/AddFirstKid/index.js
> +import KidInfo from './AddFirstKid';
Why is the name different? Won't it be misleading?

2024-08-02 14:17 UTC, Nassimancer commented on src/components/Dashboard/AddFirstKid/index.js
> +import KidInfo from './AddFirstKid';
I was working with that name, but since there are other features to add under that name, I changed it to AddFirstKid and forgot to update index.js. Sorry!

2024-08-02 22:04 UTC, AnnaSolovykh commented
@Nassimancer  please check the design system - the icon should also change its color on hover, pressed etc together withe the text. <img width="1295" alt="Screenshot 2024-08-02 at 18 03 50" src="https://github.com/user-attachments/assets/8f67d2ba-7c29-4388-a84f-0dd20998a490">

2024-08-02 22:09 UTC, AnnaSolovykh commented
1) Please export icon and picture as SVG from Figma to increase the quality. :white_check_mark: 
2) The icon color should match the color in Figma within any iteration - when we have focus or hover,  the color should change with the text as per Figma in the design system. All the colors are added by Nandini within the Custom button. Please consult her if you have issues. :heavy_minus_sign:
3) Put AddFirstKid into Kids folder :white_check_mark:
4) The pathname in Sidebar should be "kids". As it will also reflect the case when the the kid is already added. :heavy_minus_sign:
5) I can see you have added Prettier but don't see any rules for it. If you want to add let's discuss that in the group. :heavy_minus_sign:

2024-08-04 15:07 UTC, AnnaSolovykh commented on src/components/Dashboard/Kids/AddFirstKid/AddFirstKid.module.css
> +.reset-custom-button {
By the way, I suggest changing the class name as this button doesn't serve the purpose of resetting anything.

2024-08-14 01:34 UTC, ElenaCherpakova submitted a review, later dismissed

2024-08-14 18:08 UTC, AnnaSolovykh commented
1) Please export icon and picture as SVG from Figma to increase the quality. :white_check_mark: 
**2) The icon color should match the color in Figma within any iteration - when we have focus or hover,  the color should change with the text as per Figma in the design system. For now the button's outlook doesn't match fully on any iteration :heavy_minus_sign:**
3) Put AddFirstKid into Kids folder :white_check_mark:
4) The pathname in Sidebar should be "kids". As it will also reflect the case when the the kid is already added.  :white_check_mark: 
**5) I can see you have added Prettier but don't see any rules for it. If you want to add let's discuss that in the group. :heavy_minus_sign:**
6) Edit css following the comments in the PR :white_check_mark:

2024-08-22 17:36 UTC, AnnaSolovykh commented
[The solution of inheriting the color in svg in iterations](https://stackoverflow.com/questions/13000682/how-do-i-have-an-svg-image-inherit-colors-from-the-html-document)

2024-09-18 12:59 UTC, AnnaSolovykh approved these changes

2024-09-21 18:34 UTC, merged